// <auto-generated />
using System;
using BarAvenida.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarAvenida.API.Migrations
{
    [DbContext(typeof(BarAvenidaDbContext))]
    [Migration("20260505032436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarAvenida.API.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Nombre = "Comedor"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Nombre = "Terraza"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Nombre = "Barra"
                        });
                });

            modelBuilder.Entity("BarAvenida.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            ColorHex = "#F4A460",
                            Nombre = "Cervezas",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            ColorHex = "#DAA520",
                            Nombre = "Tequilas",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            ColorHex = "#DC143C",
                            Nombre = "Refrescos",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            ColorHex = "#FF6347",
                            Nombre = "Preparados",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            ColorHex = "#8B4513",
                            Nombre = "Ron",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            ColorHex = "#A0522D",
                            Nombre = "Wiskys",
                            Orden = 6
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            ColorHex = "#556B2F",
                            Nombre = "Mezcal",
                            Orden = 7
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            ColorHex = "#4682B4",
                            Nombre = "Vodkas",
                            Orden = 8
                        },
                        new
                        {
                            Id = 9,
                            Activa = true,
                            ColorHex = "#A52A2A",
                            Nombre = "Brandys",
                            Orden = 9
                        },
                        new
                        {
                            Id = 10,
                            Activa = true,
                            ColorHex = "#9370DB",
                            Nombre = "Mezcladores",
                            Orden = 10
                        },
                        new
                        {
                            Id = 11,
                            Activa = true,
                            ColorHex = "#9932CC",
                            Nombre = "Licores",
                            Orden = 11
                        },
                        new
                        {
                            Id = 12,
                            Activa = true,
                            ColorHex = "#F4E04D",
                            Nombre = "Botanas",
                            Orden = 12
                        },
                        new
                        {
                            Id = 13,
                            Activa = true,
                            ColorHex = "#B22222",
                            Nombre = "Clamatos",
                            Orden = 13
                        },
                        new
                        {
                            Id = 14,
                            Activa = true,
                            ColorHex = "#708090",
                            Nombre = "Servicios",
                            Orden = 14
                        },
                        new
                        {
                            Id = 15,
                            Activa = true,
                            ColorHex = "#696969",
                            Nombre = "Cigarros",
                            Orden = 15
                        },
                        new
                        {
                            Id = 16,
                            Activa = true,
                            ColorHex = "#4169E1",
                            Nombre = "Cubetas",
                            Orden = 16
                        },
                        new
                        {
                            Id = 17,
                            Activa = true,
                            ColorHex = "#778899",
                            Nombre = "Otros",
                            Orden = 17
                        });
                });

            modelBuilder.Entity("BarAvenida.API.Models.CorteCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentasCobradas")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalEfectivo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalTarjeta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalTransferencia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalVentas")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioAperturaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAperturaId");

                    b.HasIndex("UsuarioCierreId");

                    b.ToTable("CortesCaja");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<int>("Folio")
                        .HasColumnType("int");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<int>("MeseraId")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroPersonas")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("MeseraId");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("BarAvenida.API.Models.InventarioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CantidadActual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MetodoControl")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PesoEnvaseLleno")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PesoEnvaseVacio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoUnidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("InventarioItems");
                });

            modelBuilder.Entity("BarAvenida.API.Models.LecturaSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("LecturasSensor");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "1"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "2"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "3"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "4"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "5"
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "6"
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "7"
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "8"
                        },
                        new
                        {
                            Id = 9,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "9"
                        },
                        new
                        {
                            Id = 10,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "10"
                        },
                        new
                        {
                            Id = 11,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "11"
                        },
                        new
                        {
                            Id = 12,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "12"
                        },
                        new
                        {
                            Id = 13,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "13"
                        },
                        new
                        {
                            Id = 14,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "14"
                        },
                        new
                        {
                            Id = 15,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "15"
                        },
                        new
                        {
                            Id = 16,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "16"
                        },
                        new
                        {
                            Id = 17,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "17"
                        },
                        new
                        {
                            Id = 18,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "18"
                        },
                        new
                        {
                            Id = 19,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "19"
                        },
                        new
                        {
                            Id = 20,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "20"
                        },
                        new
                        {
                            Id = 21,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "21"
                        },
                        new
                        {
                            Id = 22,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "22"
                        },
                        new
                        {
                            Id = 23,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "23"
                        },
                        new
                        {
                            Id = 24,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "24"
                        },
                        new
                        {
                            Id = 25,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "25"
                        },
                        new
                        {
                            Id = 26,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "26"
                        },
                        new
                        {
                            Id = 27,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "27"
                        },
                        new
                        {
                            Id = 28,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "28"
                        },
                        new
                        {
                            Id = 29,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "29"
                        },
                        new
                        {
                            Id = 30,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "30"
                        },
                        new
                        {
                            Id = 31,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "31"
                        },
                        new
                        {
                            Id = 32,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "32"
                        },
                        new
                        {
                            Id = 33,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "33"
                        },
                        new
                        {
                            Id = 34,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "34"
                        },
                        new
                        {
                            Id = 35,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "35"
                        },
                        new
                        {
                            Id = 36,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "36"
                        },
                        new
                        {
                            Id = 37,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "37"
                        },
                        new
                        {
                            Id = 38,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "38"
                        },
                        new
                        {
                            Id = 39,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "39"
                        },
                        new
                        {
                            Id = 40,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "40"
                        },
                        new
                        {
                            Id = 41,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "41"
                        },
                        new
                        {
                            Id = 42,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "42"
                        },
                        new
                        {
                            Id = 43,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "43"
                        },
                        new
                        {
                            Id = 44,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "44"
                        },
                        new
                        {
                            Id = 45,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "45"
                        },
                        new
                        {
                            Id = 46,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "46"
                        },
                        new
                        {
                            Id = 47,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "47"
                        },
                        new
                        {
                            Id = 48,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "48"
                        },
                        new
                        {
                            Id = 49,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "49"
                        },
                        new
                        {
                            Id = 50,
                            Activa = true,
                            AreaId = 1,
                            Capacidad = 4,
                            Numero = "50"
                        });
                });

            modelBuilder.Entity("BarAvenida.API.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CantidadAnterior")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CantidadNueva")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventarioItemId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OrdenId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventarioItemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<bool>("EsAgregado")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaListo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("BarAvenida.API.Models.OrdenDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenDetalles");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CantidadDescuento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("InventarioItemId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoVenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("InventarioItemId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Corona",
                            Orden = 1,
                            Precio = 40m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Tecate",
                            Orden = 2,
                            Precio = 40m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Indio",
                            Orden = 3,
                            Precio = 35m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Victoria",
                            Orden = 4,
                            Precio = 40m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Ambar Corona",
                            Orden = 5,
                            Precio = 45m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Ultra Michelob",
                            Orden = 6,
                            Precio = 50m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Carta Blanca",
                            Orden = 7,
                            Precio = 35m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Caguama",
                            Orden = 8,
                            Precio = 80m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Miller Media",
                            Orden = 9,
                            Precio = 45m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Miller Caguama",
                            Orden = 10,
                            Precio = 85m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "XX Lager",
                            Orden = 11,
                            Precio = 40m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Bohemia",
                            Orden = 12,
                            Precio = 45m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Heineken",
                            Orden = 13,
                            Precio = 50m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Modelo",
                            Orden = 14,
                            Precio = 45m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Amstel Ultra",
                            Orden = 15,
                            Precio = 50m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 1,
                            Nombre = "Tecate Roja",
                            Orden = 16,
                            Precio = 40m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Cuervo Especial Shot",
                            Orden = 1,
                            Precio = 50m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Cuervo Especial Botella",
                            Orden = 2,
                            Precio = 750m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Centenario Reposado Shot",
                            Orden = 3,
                            Precio = 70m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Centenario Reposado Botella",
                            Orden = 4,
                            Precio = 900m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Hornitos Shot",
                            Orden = 5,
                            Precio = 65m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Hornitos Botella",
                            Orden = 6,
                            Precio = 850m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Tradicional Shot",
                            Orden = 7,
                            Precio = 75m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Tradicional Botella",
                            Orden = 8,
                            Precio = 950m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Don Julio 70 Shot",
                            Orden = 9,
                            Precio = 120m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Don Julio 70 Botella",
                            Orden = 10,
                            Precio = 1500m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Maestro Dobel Shot",
                            Orden = 11,
                            Precio = 110m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 31,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Maestro Dobel Botella",
                            Orden = 12,
                            Precio = 1400m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 32,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "Jimador Shot",
                            Orden = 13,
                            Precio = 60m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 33,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 2,
                            Nombre = "1800 Cristalino Shot",
                            Orden = 14,
                            Precio = 130m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 40,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 3,
                            Nombre = "Coca",
                            Orden = 1,
                            Precio = 30m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 41,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 3,
                            Nombre = "Fresca",
                            Orden = 2,
                            Precio = 30m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 42,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 3,
                            Nombre = "Agua Mineral",
                            Orden = 3,
                            Precio = 30m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 43,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 3,
                            Nombre = "Agua Natural",
                            Orden = 4,
                            Precio = 25m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 50,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 5,
                            Nombre = "Bacardi Carta Blanca Shot",
                            Orden = 1,
                            Precio = 60m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 51,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 5,
                            Nombre = "Bacardi Carta Blanca Botella",
                            Orden = 2,
                            Precio = 800m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 52,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 5,
                            Nombre = "Bacardi Añejo Shot",
                            Orden = 3,
                            Precio = 70m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 53,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 5,
                            Nombre = "Capitan Morgan Shot",
                            Orden = 4,
                            Precio = 75m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 54,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 5,
                            Nombre = "Capitan Morgan Botella",
                            Orden = 5,
                            Precio = 900m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 55,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 5,
                            Nombre = "Bacardi Solera Shot",
                            Orden = 6,
                            Precio = 80m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 56,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 5,
                            Nombre = "Bacardi Solera Botella",
                            Orden = 7,
                            Precio = 950m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 57,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 5,
                            Nombre = "Matusalem Botella",
                            Orden = 8,
                            Precio = 1100m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 60,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Buchanans 12 Shot",
                            Orden = 1,
                            Precio = 130m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 61,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Buchanans 12 Botella",
                            Orden = 2,
                            Precio = 1800m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 62,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Buchanans 18 Shot",
                            Orden = 3,
                            Precio = 200m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 63,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Buchanans 18 Botella",
                            Orden = 4,
                            Precio = 2800m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 64,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Jack Daniels Shot",
                            Orden = 5,
                            Precio = 130m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 65,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Jack Daniels Botella",
                            Orden = 6,
                            Precio = 1800m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 66,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Jack Daniels Honey Shot",
                            Orden = 7,
                            Precio = 140m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 67,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Black Label Shot",
                            Orden = 8,
                            Precio = 150m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 68,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Black Label Botella",
                            Orden = 9,
                            Precio = 2100m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 69,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Red Label Shot",
                            Orden = 10,
                            Precio = 110m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 70,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Red Label Botella",
                            Orden = 11,
                            Precio = 1500m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 71,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Chivas Regal Shot",
                            Orden = 12,
                            Precio = 130m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 72,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Black White Shot",
                            Orden = 13,
                            Precio = 100m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 73,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "William Lawson Shot",
                            Orden = 14,
                            Precio = 90m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 74,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 6,
                            Nombre = "Passport Shot",
                            Orden = 15,
                            Precio = 85m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 80,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 7,
                            Nombre = "Cuatrocientos Conejos Shot",
                            Orden = 1,
                            Precio = 90m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 81,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 7,
                            Nombre = "Cuatrocientos Conejos Botella",
                            Orden = 2,
                            Precio = 1100m,
                            TipoVenta = "Botella"
                        },
                        new
                        {
                            Id = 82,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 7,
                            Nombre = "Amaras Reposado Shot",
                            Orden = 3,
                            Precio = 100m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 90,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 8,
                            Nombre = "Smirnoff Shot",
                            Orden = 1,
                            Precio = 70m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 91,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 8,
                            Nombre = "Smirnoff Tamarindo Shot",
                            Orden = 2,
                            Precio = 75m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 92,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 8,
                            Nombre = "Absolut Shot",
                            Orden = 3,
                            Precio = 90m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 93,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 8,
                            Nombre = "Wiborowa Shot",
                            Orden = 4,
                            Precio = 70m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 94,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 8,
                            Nombre = "Oso Negro Shot",
                            Orden = 5,
                            Precio = 60m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 100,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 9,
                            Nombre = "Torres 10 Shot",
                            Orden = 1,
                            Precio = 80m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 101,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 9,
                            Nombre = "Don Pedro Shot",
                            Orden = 2,
                            Precio = 60m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 102,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 9,
                            Nombre = "Presidente Shot",
                            Orden = 3,
                            Precio = 65m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 110,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 11,
                            Nombre = "Baileys Shot",
                            Orden = 1,
                            Precio = 90m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 111,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 11,
                            Nombre = "Licor 43 Shot",
                            Orden = 2,
                            Precio = 90m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 120,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 13,
                            Nombre = "Clamato Chico",
                            Orden = 1,
                            Precio = 60m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 121,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 13,
                            Nombre = "Clamato Grande",
                            Orden = 2,
                            Precio = 90m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 122,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 13,
                            Nombre = "Michelada Chica",
                            Orden = 3,
                            Precio = 70m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 123,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 13,
                            Nombre = "Michelada Grande",
                            Orden = 4,
                            Precio = 100m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 130,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 4,
                            Nombre = "Vampiro",
                            Orden = 1,
                            Precio = 100m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 131,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 4,
                            Nombre = "Paloma",
                            Orden = 2,
                            Precio = 90m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 132,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 4,
                            Nombre = "Limonada Grande",
                            Orden = 3,
                            Precio = 60m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 133,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 4,
                            Nombre = "Limonada Chica",
                            Orden = 4,
                            Precio = 40m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 134,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 4,
                            Nombre = "Sangrita Shot",
                            Orden = 5,
                            Precio = 35m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 135,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 4,
                            Nombre = "Limon Concentrado Shot",
                            Orden = 6,
                            Precio = 25m,
                            TipoVenta = "Shot"
                        },
                        new
                        {
                            Id = 140,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 15,
                            Nombre = "Cigarro Blanco",
                            Orden = 1,
                            Precio = 100m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 141,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 15,
                            Nombre = "Cigarro Rojo",
                            Orden = 2,
                            Precio = 100m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 150,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 12,
                            Nombre = "Cacahuates",
                            Orden = 1,
                            Precio = 50m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 151,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 12,
                            Nombre = "Papas Diversas",
                            Orden = 2,
                            Precio = 60m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 152,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 12,
                            Nombre = "Pistaches",
                            Orden = 3,
                            Precio = 70m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 153,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 12,
                            Nombre = "Carne Seca",
                            Orden = 4,
                            Precio = 90m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 154,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 12,
                            Nombre = "Charales",
                            Orden = 5,
                            Precio = 60m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 155,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 12,
                            Nombre = "Camarones",
                            Orden = 6,
                            Precio = 120m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 156,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 12,
                            Nombre = "Chicharrones",
                            Orden = 7,
                            Precio = 70m,
                            TipoVenta = "Pieza"
                        },
                        new
                        {
                            Id = 160,
                            Activo = true,
                            CantidadDescuento = 1m,
                            CategoriaId = 14,
                            Nombre = "Billar Hora",
                            Orden = 1,
                            Precio = 100m,
                            TipoVenta = "Pieza"
                        });
                });

            modelBuilder.Entity("BarAvenida.API.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EnLinea")
                        .HasColumnType("bit");

                    b.Property<string>("IdHardware")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UltimoHeartbeat")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdHardware")
                        .IsUnique();

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "ADMIN",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Coronado",
                            PinHash = "$2a$11$KU/QP6s5mK4YUqWEugxt4ed7b.HtQI3SzqTYfBcYv7pz3uIFhRJCa",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "23",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "ABBY GZZ",
                            PinHash = "$2a$11$txNeaEMqmZmifGpvJJ2H2O9ByXgnNkTYbSZpE6lRHJNUi.xbFTwLO",
                            Rol = "Mesera"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "28",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "IRIS",
                            PinHash = "$2a$11$txNeaEMqmZmifGpvJJ2H2O9ByXgnNkTYbSZpE6lRHJNUi.xbFTwLO",
                            Rol = "Mesera"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "BAR1",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Barman 1",
                            PinHash = "$2a$11$mIXN5YLqK9H3eJQl2ZQi2.E2Cf9VIJBeXgqBNNeBJmO9K/oLws9Ae",
                            Rol = "Barman"
                        });
                });

            modelBuilder.Entity("BarAvenida.API.Models.CorteCaja", b =>
                {
                    b.HasOne("BarAvenida.API.Models.Usuario", "UsuarioApertura")
                        .WithMany()
                        .HasForeignKey("UsuarioAperturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BarAvenida.API.Models.Usuario", "UsuarioCierre")
                        .WithMany()
                        .HasForeignKey("UsuarioCierreId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Cuenta", b =>
                {
                    b.HasOne("BarAvenida.API.Models.Mesa", "Mesa")
                        .WithMany("Cuentas")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarAvenida.API.Models.Usuario", "Mesera")
                        .WithMany()
                        .HasForeignKey("MeseraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Mesera");
                });

            modelBuilder.Entity("BarAvenida.API.Models.InventarioItem", b =>
                {
                    b.HasOne("BarAvenida.API.Models.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("BarAvenida.API.Models.LecturaSensor", b =>
                {
                    b.HasOne("BarAvenida.API.Models.Sensor", "Sensor")
                        .WithMany("Lecturas")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Mesa", b =>
                {
                    b.HasOne("BarAvenida.API.Models.Area", "Area")
                        .WithMany("Mesas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("BarAvenida.API.Models.MovimientoInventario", b =>
                {
                    b.HasOne("BarAvenida.API.Models.InventarioItem", "InventarioItem")
                        .WithMany("Movimientos")
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarAvenida.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("InventarioItem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Orden", b =>
                {
                    b.HasOne("BarAvenida.API.Models.Cuenta", "Cuenta")
                        .WithMany("Ordenes")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("BarAvenida.API.Models.OrdenDetalle", b =>
                {
                    b.HasOne("BarAvenida.API.Models.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarAvenida.API.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Producto", b =>
                {
                    b.HasOne("BarAvenida.API.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarAvenida.API.Models.InventarioItem", "InventarioItem")
                        .WithMany()
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("InventarioItem");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Area", b =>
                {
                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Cuenta", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("BarAvenida.API.Models.InventarioItem", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Mesa", b =>
                {
                    b.Navigation("Cuentas");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Orden", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BarAvenida.API.Models.Sensor", b =>
                {
                    b.Navigation("Lecturas");
                });
#pragma warning restore 612, 618
        }
    }
}
